name = "testmodpack"
author = "Exo505"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e95db22f8942888b9bb8188cec7dbd38fe9442f1165506e2683c1f9af91ecb4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.229"
